name: Epoch

options:
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15"

targets:
  Epoch:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Epoch
        excludes:
          - Resources
    resources:
      - path: Epoch/Resources
        excludes:
          - "*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: de.nfelger.epoch
        SWIFT_VERSION: "5.9"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: Epoch/Resources/Epoch.entitlements
        MACOSX_DEPLOYMENT_TARGET: "14.0"
    info:
      path: Epoch/Info.plist
      properties:
        LSUIElement: true
        CFBundleDisplayName: Epoch
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"

  EpochTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: EpochTests
    dependencies:
      - target: Epoch
    settings:
      base:
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        GENERATE_INFOPLIST_FILE: YES
